FROM python:3.6-stretch

WORKDIR /app/

RUN pip install pipenv

COPY Pipfile Pipfile.lock /app/
RUN pipenv install --system --deploy

COPY main.py __init__.py /app/
COPY models/ /app/models/

# ENTRYPOINT /bin/bash
EXPOSE 5000

CMD ["python","-u","main.py"]
