version: "3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 8000:5000
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8001:5000